version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: scripts/prelims.sh
      timeout: 300
      runas: ec2-user   
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user

