version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/tutorial
permissions:
  - object: /home/ec2-user/tutorial
    owner: ec2-user
    group: ec2-user
    type:
      - file
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user
